apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: app.fib.exam.ly
spec:
  secretName: app.fib.exam.ly
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.fib.exam.ly
  dnsNames:
    - app.fib.exam.ly
